
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!! Automatically generated by make_options_def.py. !!!
// !!! do not edit manually                            !!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#ifndef __OPTIONS_HH__
#define __OPTIONS_HH__

const char* option_defs[] = {
"__PACKAGE_TRIM__", "",
"__HAVE_SYS_TIME_H__", "1",
"__COMPILER__", "\"/usr/bin/c++\"",
"__PACKAGE_UIDS__", "",
"__HAVE_TIME_H__", "1",
"__PACKAGE_CORE__", "",
"__PACKAGE_DB__", "",
"__TIME_WITH_SYS_TIME__", "1",
"__PACKAGE_FFI__", "",
"__PACKAGE_CRYPTO__", "",
"__ED_INDENT_SPACES__", "4",
"__REF_RESERVED_WORD__", "",
"__PACKAGES_PACKAGES_H__", "",
"__CFG_MAX_CALL_DEPTH__", "150",
"__PACKAGE_COMPRESS__", "",
"__SAVE_EXTENSION__", "\".o\"",
"__HAVE_SYS_RESOURCE_H__", "1",
"__PROJECT_VERSION__", "\"fluffos -16c57df\"",
"__PACKAGE_PCRE__", "",
"__PACKAGE_MATH__", "",
"__SMALL_STRING_SIZE__", "100",
"__PACKAGE_DEVELOP__", "",
"__LARGEST_PRINTABLE_STRING__", "65535",
"__HAVE_JEMALLOC__", "1",
"__PARSE_DEBUG__", "",
"__PACKAGE_OPS__", "",
"__RESTRICTED_ED__", "",
"__CFG_COMPILER_STACK_SIZE__", "600",
"__LARGE_STRING_SIZE__", "1000",
"__PACKAGE_MATRIX__", "",
"__PRIVS__", "",
"__COMMAND_BUF_SIZE__", "2000",
"__OLD_ED__", "",
"__PACKAGE_PARSER__", "",
"__PACKAGE_EXTERNAL__", "",
"__PACKAGE_CONTRIB__", "",
"__HAVE_DIRENT_H__", "1",
"__STRUCT_CLASS__", "",
"__USE_32BIT_ADDRESSES__", "",
"__CFG_MAX_GLOBAL_VARIABLES__", "65536",
"__PACKAGE_SOCKETS__", "",
"__SAVE_GZ_EXTENSION__", "\".o.gz\"",
"__HAVE_SIGNAL_H__", "1",
"__DEFAULT_PRAGMAS__", "PRAGMA_WARNINGS + PRAGMA_SAVE_TYPES + PRAGMA_ERROR_CONTEXT + PRAGMA_OPTIMIZE",
"__MAX_SAVE_SVALUE_DEPTH__", "100",
"__AUTO_SETEUID__", "",
"__HAVE_SYS_STAT_H__", "1",
"__CXXFLAGS__", "\"Broken\"",
"__ED_TAB_WIDTH__", "8",
"__PACKAGE_SHA1__", "",
"__STRUCT_STRUCT__", "",
"__PACKAGE_ASYNC__", "",
"__CFG_EVALUATOR_STACK_SIZE__", "65536",
"__PACKAGE_MUDLIB_STATS__", "",
"__SENSIBLE_MODIFIERS__", "",

};

#endif // __OPTIONS_HH__
