#ifndef PACKAGES_PACKAGES_H
#define PACKAGES_PACKAGES_H

#define PACKAGE_ASYNC
#define PACKAGE_COMPRESS
#define PACKAGE_CONTRIB
#define PACKAGE_CORE
#define PACKAGE_CRYPTO
#define PACKAGE_DB
#define PACKAGE_DEVELOP
#define PACKAGE_EXTERNAL
#define PACKAGE_FFI
#define PACKAGE_MATH
#define PACKAGE_MATRIX
#define PACKAGE_MUDLIB_STATS
#define PACKAGE_OPS
#define PACKAGE_PARSER
#define PACKAGE_PCRE
#define PACKAGE_SHA1
#define PACKAGE_SOCKETS
#define PACKAGE_TRIM
#define PACKAGE_UIDS

#endif /* PACKAGES_PACKAGES_H */ 
